name: 'Build Grapphs'
description: 'Compiles grapphs with all configurations'

inputs:
  build-folder:
    description: Build folder of where to compile all configurations
    required: true
  build-type:
    description: Which build types to use
    required: true
  configure:
    description: Whether we should also
    required: false
    default: true
  targets:
    description: Which targets to compile
    required: false
    default: grapphs grapphs-graphviz grapphs-svg
  cmake_args:
    description: Arguments to pass onto cmake
    required: false
    default: -DGRAPPHS_COMPILE_SAMPLES=Off -DGRAPPHS_COMPILE_TESTS=Off

runs:
  using: composite
  steps:
    - if: ${{ inputs.configure }}
      uses: ./.github/actions/setup-grapphs

    - if: ${{ inputs.configure }}
      name: Configure CMake
      shell: bash
      run: cmake -B ${{ inputs.build-folder }} -G "Ninja Multi-Config" ${{ inputs.cmake_args }} ${{ github.workspace }}

    - name: Build
      shell: bash
      run: cmake --build ${{ inputs.build-folder }} --target ${{ inputs.targets }} --config ${{ inputs.build-type }}