macro(grapphs_bootstrap)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY bin)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})

    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY lib)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})

    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY lib)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})

    set(CMAKE_DEBUG_POSTFIX -d)
    set(CMAKE_RELWITHDEBINFO_POSTFIX -rel-d)
    set(CMAKE_MINSIZEREL_POSTFIX -minsizerel)
endmacro()

function(grapphs_set_target_output_directory_same_as TARGET OTHER_TARGET)
    set_target_properties(
            ${TARGET}
            PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},RUNTIME_OUTPUT_DIRECTORY>"
            RUNTIME_OUTPUT_DIRECTORY_DEBUG "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},RUNTIME_OUTPUT_DIRECTORY_DEBUG>"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},RUNTIME_OUTPUT_DIRECTORY_RELEASE>"
            RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO>"
            RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL>"
            ARCHIVE_OUTPUT_DIRECTORY "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},ARCHIVE_OUTPUT_DIRECTORY>"
            ARCHIVE_OUTPUT_DIRECTORY_DEBUG "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},ARCHIVE_OUTPUT_DIRECTORY_DEBUG>"
            ARCHIVE_OUTPUT_DIRECTORY_RELEASE "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},ARCHIVE_OUTPUT_DIRECTORY_RELEASE>"
            ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO>"
            ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL>"
            LIBRARY_OUTPUT_DIRECTORY "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},LIBRARY_OUTPUT_DIRECTORY>"
            LIBRARY_OUTPUT_DIRECTORY_DEBUG "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},LIBRARY_OUTPUT_DIRECTORY_DEBUG>"
            LIBRARY_OUTPUT_DIRECTORY_RELEASE "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},LIBRARY_OUTPUT_DIRECTORY_RELEASE>"
            LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO>"
            LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "$<TARGET_PROPERTY:${OTHER_TARGET},BINARY_DIR>/$<TARGET_PROPERTY:${OTHER_TARGET},LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL>"
    )
endfunction()