name: Package

on:
  workflow_dispatch: { }
  workflow_call: { }

jobs:
  package:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: package-grapphs
        uses: ./.github/actions/package-grapphs
        with:
          build-folder: build/
          package-folder: package/
      - run: tree ${{ steps.package-grapphs.outputs.package-folder }}
      - uses: actions/upload-artifact@v3
        with:
          name: grapphs-${{ matrix.os }}-packages
          path: |
            ${{ steps.package-grapphs.outputs.package-folder }}/*
            !${{ steps.package-grapphs.outputs.package-folder }}/_CPack_Packages/