name: Release

on:
  workflow_dispatch: {}

jobs:
  prepare_artifacts:
    uses: ./.github/workflows/package.yml
  create_release_draft:
    runs-on: ubuntu-latest
    needs: prepare_artifacts
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            artifacts/**