name: Test

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  workflow_dispatch: { }

env:
  BUILD_TYPE: RelWithDebInfo
  CONAN_DATA_DIRECTORY: ~/.conan/data
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-grapphs
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: .github/requirements.package.txt

      - name: Install Python Dependencies
        run: pip install -r .github/requirements.package.txt

      - name: Restore Conan Dependencies
        id: conan-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CONAN_DATA_DIRECTORY }}
          key: ${{ runner.os }}-conan

      - name: Restore Mazes
        id: maze-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}/build/bin/mazes
          key: ${{ runner.os }}-mazes

      - name: Build CMake
        uses: ./.github/actions/build-grapphs
        with:
          build-folder: build/
          build-type: ${{env.BUILD_TYPE}}
          targets: grapphs-tests grapphs-graphviz-tests
          cmake_args: -DGRAPPHS_COMPILE_SAMPLES=Off -DGRAPPHS_COMPILE_TESTS=On

      - name: Save Conan Dependencies
        uses: actions/cache/save@v3
        if: steps.conan-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.CONAN_DATA_DIRECTORY }}
          key: ${{ runner.os }}-conan

      - name: Save Mazes
        uses: actions/cache/restore@v3
        if: steps.maze-cache.outputs.cache-hit != 'true'
        with:
          path: ${{github.workspace}}/build/bin/mazes
          key: ${{ runner.os }}-mazes

      - name: Test grapphs
        working-directory: ${{github.workspace}}/build/tests/bin
        run: ./grapphs-tests

      - name: Test grapphs-graphviz
        working-directory: ${{github.workspace}}/build/tests/bin
        run: ./grapphs-graphviz-tests